#
# Configuration for GitHub-based CI, based on the stock GitHub Rust config.
#
name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
    - uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
      with:
        toolchain: stable
        default: false
        components: rustfmt
    - name: Check style
      run: cargo fmt -- --check

  check-without-cockroach:
    runs-on: ubuntu-latest
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
    - name: Cargo check
      run: cargo check --no-default-features

  build-and-test-macos-14:
    runs-on: macos-14
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
    - name: Link libpq
      run: brew link --force libpq
    - name: Build
      run: cargo build --tests --verbose
    - name: Run tests
      run: cargo test --verbose

  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
    - name: Build
      run: cargo build --tests --verbose
    - name: Run tests
      run: cargo test --verbose
